services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    networks:
      reverse-proxy-network:
        aliases:
          - reverse-proxy-container
    environment:
      DOMAIN: ${CADDY_DOMAIN}
      EMAIL: ${CADDY_EMAIL}
      CONTAINER_NAME: ${CADDY_CONTAINER_NAME}
      PORT: ${CADDY_PORT}

networks:
  reverse-proxy-network:
    external: true